### PR TITLE
Cleaner Proxy Fix

### PR DESCRIPTION
**Pull request by InvestYGator**
Remove the proxy check here.

### CODE REVIEW

**Comment by antiosh** [comment]
Won't this just end up trying to send more things to the api resulting in the unsupported error?

image

**Comment by antiosh** [comment]
I think you need to look at this: https://github.com/steem-monsters/splinterlands-js/blob/edacb37a650d386bf90f7e932297381cf61be2d5/src/splinterlands.js#L486 ?
https://github.com/steem-monsters/splinterlands-js/blob/edacb37a650d386bf90f7e932297381cf61be2d5/src/splinterlands.js#L568

**Comment by InvestYGator** [comment]
> I think you need to look at this:
> 
> https://github.com/steem-monsters/splinterlands-js/blob/edacb37a650d386bf90f7e932297381cf61be2d5/src/splinterlands.js#L486
> 
> ?
> https://github.com/steem-monsters/splinterlands-js/blob/edacb37a650d386bf90f7e932297381cf61be2d5/src/splinterlands.js#L568

After spending a lot of the day looking at how this works on the web-site, I think I understand how Proxy works.  The issue here was that battle API calls were not being made to the API because of this Proxy check.  If it is an API operation, line 486 fails the IF check and goes into the send_tx method.  With the original check (before PR 29), it would skip doing anything, and fail down to Line 540 where it would send it as an old transaction with the Proxy broadcast.   It should go to the server_broadcast_tx and try to hit the API, even for free-to-play accounts, rather than front the transaction to the Proxy broadcast.

This is basically just cleaning up that the proxy check doesn't need to be done here.  This code should only be reached for API calls, and anything else would have already failed the check on line 486.  Proxy shouldn't matter for broadcasting to an API, only for broadcasting to the chain (or, via the broadcast service to the chain).

**Review by antiosh — APPROVED** [review]

**Comment by antiosh** [comment]
Ok. i'll approve :D 
I guess you can test by doing a publish-dev and seeing how mobile qa works: https://m-qa.splinterlands.com/

**Comment by Melonman0** [comment]
I tested this on mobile QA and it works. Merging and will push to PROD

**Pull request merged**
